let
    BaseUrl = "https://veristream-services.atlassian.net/rest/api/3/search?jql=issuetype in ('Sub-task')&expand=names",
    JiraIDPerPage = 50,
 
    GetJson = (Url) =>
        let 
            RawData = Web.Contents(Url),
            Json    = Json.Document(RawData)
        in  Json,
 
    GetJiraIDCount = () =>
        let Url   = BaseUrl & "&maxResults=0",
            Json  = GetJson(Url),
            Count = Json[#"total"]
        in  Count,
 
    GetPage = (Index) =>
        let Skip  = "&startAt=" & Text.From(Index * JiraIDPerPage),
            Top   = "&maxResults=" & Text.From(JiraIDPerPage),
            Url   = BaseUrl & Skip & Top,
            Json  = GetJson(Url),
            Value = Json[#"issues"]
        in  Value,
 
    JiraIDCount = List.Max({ JiraIDPerPage, GetJiraIDCount() }),
    PageCount   = Number.RoundUp(JiraIDCount / JiraIDPerPage),
    PageIndices = { 0 .. PageCount },
    Pages       = List.Transform(PageIndices, each GetPage(_)),
    JiraID      = List.Union(Pages),
    Table       = Table.FromList(JiraID, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(Table, "Column1", {"expand", "id", "self", "key", "fields"}, {"Column1.expand", "Column1.id", "Column1.self", "Column1.key", "Column1.fields"}),
    #"Expanded Column1.fields" = Table.ExpandRecordColumn(#"Expanded Column1", "Column1.fields", {"statuscategorychangedate", "issuetype", "customfield_10030", "project", "customfield_10033", "customfield_10034", "resolution", "customfield_10035", "customfield_10036", "customfield_10037", "customfield_10027", "customfield_10028", "customfield_10029", "resolutiondate", "created", "customfield_10020", "customfield_10021", "customfield_10022", "priority", "customfield_10023", "customfield_10024", "customfield_10025", "customfield_10026", "customfield_10016", "customfield_10017", "customfield_10018", "customfield_10019", "timeestimate", "aggregatetimeoriginalestimate", "assignee", "updated", "status", "timeoriginalestimate", "description", "customfield_10010", "customfield_10014", "customfield_10015", "customfield_10005", "customfield_10006", "customfield_10007", "customfield_10008", "aggregatetimeestimate", "customfield_10009", "summary", "creator", "customfield_10000", "customfield_10001", "customfield_10002", "customfield_10003", "customfield_10004", "customfield_10038", "environment", "duedate"}, {"Column1.fields.statuscategorychangedate", "Column1.fields.issuetype", "Column1.fields.customfield_10030", "Column1.fields.project", "Column1.fields.customfield_10033", "Column1.fields.customfield_10034", "Column1.fields.resolution", "Column1.fields.customfield_10035", "Column1.fields.customfield_10036", "Column1.fields.customfield_10037", "Column1.fields.customfield_10027", "Column1.fields.customfield_10028", "Column1.fields.customfield_10029", "Column1.fields.resolutiondate", "Column1.fields.created", "Column1.fields.customfield_10020", "Column1.fields.customfield_10021", "Column1.fields.customfield_10022", "Column1.fields.priority", "Column1.fields.customfield_10023", "Column1.fields.customfield_10024", "Column1.fields.customfield_10025", "Column1.fields.customfield_10026", "Column1.fields.customfield_10016", "Column1.fields.customfield_10017", "Column1.fields.customfield_10018", "Column1.fields.customfield_10019", "Column1.fields.timeestimate", "Column1.fields.aggregatetimeoriginalestimate", "Column1.fields.assignee", "Column1.fields.updated", "Column1.fields.status", "Column1.fields.timeoriginalestimate", "Column1.fields.description", "Column1.fields.customfield_10010", "Column1.fields.customfield_10014", "Column1.fields.customfield_10015", "Column1.fields.customfield_10005", "Column1.fields.customfield_10006", "Column1.fields.customfield_10007", "Column1.fields.customfield_10008", "Column1.fields.aggregatetimeestimate", "Column1.fields.customfield_10009", "Column1.fields.summary", "Column1.fields.creator", "Column1.fields.customfield_10000", "Column1.fields.customfield_10001", "Column1.fields.customfield_10002", "Column1.fields.customfield_10003", "Column1.fields.customfield_10004", "Column1.fields.customfield_10038", "Column1.fields.environment", "Column1.fields.duedate"}),
    #"Expanded Column1.fields.issuetype" = Table.ExpandRecordColumn(#"Expanded Column1.fields", "Column1.fields.issuetype", {"id", "description", "name"}, {"Column1.fields.issuetype.id", "Column1.fields.issuetype.description", "Column1.fields.issuetype.name"}),
    #"Expanded Column1.fields.project" = Table.ExpandRecordColumn(#"Expanded Column1.fields.issuetype", "Column1.fields.project", {"id", "key", "name"}, {"Column1.fields.project.id", "Column1.fields.project.key", "Column1.fields.project.name"}),
    #"Expanded Column1.fields.resolution" = Table.ExpandRecordColumn(#"Expanded Column1.fields.project", "Column1.fields.resolution", {"id", "name"}, {"Column1.fields.resolution.id", "Column1.fields.resolution.name"}),
    #"Expanded Column1.fields.customfield_10037" = Table.ExpandRecordColumn(#"Expanded Column1.fields.resolution", "Column1.fields.customfield_10037", {"value", "id"}, {"Column1.fields.customfield_10037.value", "Column1.fields.customfield_10037.id"}),
    #"Expanded Column1.fields.priority" = Table.ExpandRecordColumn(#"Expanded Column1.fields.customfield_10037", "Column1.fields.priority", {"name", "id"}, {"Column1.fields.priority.name", "Column1.fields.priority.id"}),
    #"Expanded Column1.fields.customfield_10018" = Table.ExpandRecordColumn(#"Expanded Column1.fields.priority", "Column1.fields.customfield_10018", {"hasEpicLinkFieldDependency", "showField", "nonEditableReason"}, {"Column1.fields.customfield_10018.hasEpicLinkFieldDependency", "Column1.fields.customfield_10018.showField", "Column1.fields.customfield_10018.nonEditableReason"}),
    #"Expanded Column1.fields.customfield_10018.nonEditableReason" = Table.ExpandRecordColumn(#"Expanded Column1.fields.customfield_10018", "Column1.fields.customfield_10018.nonEditableReason", {"reason", "message"}, {"Column1.fields.customfield_10018.nonEditableReason.reason", "Column1.fields.customfield_10018.nonEditableReason.message"}),
    #"Expanded Column1.fields.assignee" = Table.ExpandRecordColumn(#"Expanded Column1.fields.customfield_10018.nonEditableReason", "Column1.fields.assignee", {"accountId", "emailAddress", "displayName"}, {"Column1.fields.assignee.accountId", "Column1.fields.assignee.emailAddress", "Column1.fields.assignee.displayName"}),
    #"Expanded Column1.fields.status" = Table.ExpandRecordColumn(#"Expanded Column1.fields.assignee", "Column1.fields.status", {"description", "name", "id", "statusCategory"}, {"Column1.fields.status.description", "Column1.fields.status.name", "Column1.fields.status.id", "Column1.fields.status.statusCategory"}),
    #"Expanded Column1.fields.status.statusCategory" = Table.ExpandRecordColumn(#"Expanded Column1.fields.status", "Column1.fields.status.statusCategory", {"id", "key", "name"}, {"Column1.fields.status.statusCategory.id", "Column1.fields.status.statusCategory.key", "Column1.fields.status.statusCategory.name"}),
    #"Expanded Column1.fields.description" = Table.ExpandRecordColumn(#"Expanded Column1.fields.status.statusCategory", "Column1.fields.description", {"version", "type", "content"}, {"Column1.fields.description.version", "Column1.fields.description.type", "Column1.fields.description.content"}),
    #"Expanded Column1.fields.creator" = Table.ExpandRecordColumn(#"Expanded Column1.fields.description", "Column1.fields.creator", {"accountId", "displayName"}, {"Column1.fields.creator.accountId", "Column1.fields.creator.displayName"}),
    #"Expanded Column1.fields.customfield_10038" = Table.ExpandRecordColumn(#"Expanded Column1.fields.creator", "Column1.fields.customfield_10038", {"value", "id"}, {"Column1.fields.customfield_10038.value", "Column1.fields.customfield_10038.id"}),
    #"Removed Columns" = Table.RemoveColumns(#"Expanded Column1.fields.customfield_10038",{"Column1.expand", "Column1.id", "Column1.self", "Column1.fields.issuetype.id", "Column1.fields.issuetype.description", "Column1.fields.customfield_10030", "Column1.fields.project.id", "Column1.fields.customfield_10033", "Column1.fields.customfield_10034", "Column1.fields.resolution.id", "Column1.fields.customfield_10035", "Column1.fields.customfield_10036", "Column1.fields.customfield_10037.id", "Column1.fields.customfield_10027", "Column1.fields.customfield_10028", "Column1.fields.customfield_10029", "Column1.fields.customfield_10020", "Column1.fields.customfield_10021", "Column1.fields.customfield_10022", "Column1.fields.priority.id", "Column1.fields.customfield_10023", "Column1.fields.customfield_10024", "Column1.fields.customfield_10025", "Column1.fields.customfield_10026", "Column1.fields.customfield_10016", "Column1.fields.customfield_10017", "Column1.fields.customfield_10018.hasEpicLinkFieldDependency", "Column1.fields.customfield_10018.showField", "Column1.fields.customfield_10018.nonEditableReason.reason", "Column1.fields.customfield_10018.nonEditableReason.message", "Column1.fields.customfield_10019", "Column1.fields.timeestimate", "Column1.fields.aggregatetimeoriginalestimate", "Column1.fields.assignee.accountId", "Column1.fields.assignee.emailAddress", "Column1.fields.status.description", "Column1.fields.status.id", "Column1.fields.status.statusCategory.id", "Column1.fields.status.statusCategory.key", "Column1.fields.status.statusCategory.name", "Column1.fields.timeoriginalestimate", "Column1.fields.description.version", "Column1.fields.description.type", "Column1.fields.description.content", "Column1.fields.customfield_10010", "Column1.fields.customfield_10015", "Column1.fields.customfield_10005", "Column1.fields.customfield_10006", "Column1.fields.customfield_10007", "Column1.fields.customfield_10008", "Column1.fields.aggregatetimeestimate", "Column1.fields.customfield_10009", "Column1.fields.creator.accountId", "Column1.fields.customfield_10000", "Column1.fields.customfield_10001", "Column1.fields.customfield_10002", "Column1.fields.customfield_10003", "Column1.fields.customfield_10004", "Column1.fields.customfield_10038.id", "Column1.fields.environment"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Column1.key", "Task Key"}, {"Column1.fields.statuscategorychangedate", "Status Change Time"}, {"Column1.fields.issuetype.name", "Issue Type"}, {"Column1.fields.project.key", "Project Key"}, {"Column1.fields.project.name", "Project Name"}, {"Column1.fields.resolution.name", "Resolution"}, {"Column1.fields.customfield_10037.value", "Customer"}, {"Column1.fields.resolutiondate", "Resolution Time"}, {"Column1.fields.created", "Created Time"}, {"Column1.fields.priority.name", "Priority"}, {"Column1.fields.assignee.displayName", "Assignee"}, {"Column1.fields.updated", "Updated Time"}, {"Column1.fields.status.name", "Status"}, {"Column1.fields.customfield_10014", "Epic Key"}, {"Column1.fields.summary", "Task Name"}, {"Column1.fields.creator.displayName", "Created By"}, {"Column1.fields.customfield_10038.value", "Product"}, {"Column1.fields.duedate", "Due Date"}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"Epic Key"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"Task Name", "Sub-task Name"}, {"Task Key", "Sub-task Key"}})
in
    #"Renamed Columns1"